{
 "title": "ChainAccess",
 "time": { "from": "2019-11-25T02:38:04.823Z", "to": "2019-11-25T03:25:31.761Z" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "k8s_cluster",
    "query": "label_values(kube_node_status_allocatable_cpu_cores,k8s_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "system_cpu_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (application,instance) (system_cpu_usage{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"}/system_cpu_count{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "jvm_gc_pause_per_minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, application, action, cause) (rate (jvm_gc_pause_seconds_count{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"}[5m])) * 60"
    }
   ]
  },
  {
   "title": "jvm_gc_pause_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, application, action, cause)(delta(jvm_gc_pause_seconds_sum{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"}[5m])/delta(jvm_gc_pause_seconds_count{application=~\"chainAccess.*\"}[5m])>0)"
    }
   ]
  },
  {
   "title": "jvm_heap_usage_percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,application,area,id) (jvm_memory_used_bytes{application=~\"chainAccess.*\",area=\"heap\",k8s_cluster=\"$k8s_cluster\"}/jvm_memory_committed_bytes{application=~\"chainAccess.*\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "chain_connector_web3jMap_size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "chain_connector_web3jMap_size{application=\"chainAccessPipe\",k8s_cluster=\"$k8s_cluster\"}"
    }
   ]
  },
  {
   "title": "http_server_requests_per_minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, application) (irate(http_server_requests_seconds_count{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"}[2m])) * 60"
    }
   ]
  },
  {
   "title": "http_server_requests_response_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, application, uri, method)(delta(http_server_requests_seconds_sum{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"}[2m])/delta(http_server_requests_seconds_count{application=~\"chainAccess.*\"}[2m])>0)"
    }
   ]
  },
  {
   "title": "chain_connector_updateMap_total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "chain_connector_updateMap_time_total{application=\"chainAccessPipe\",k8s_cluster=\"$k8s_cluster\"}"
    }
   ]
  },
  {
   "title": "zookeeper_send_notification_total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "zookeeper_send_notification_time_total{application=\"chainAccessAdmin\",path=\"/pipe/project_blockchain_notification\",k8s_cluster=\"$k8s_cluster\"}"
    }
   ]
  },
  {
   "title": "chain_connector_web3jMap_project_chain_size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,application,projectId) (chain_connector_web3jMap_project_chain_size{application=\"chainAccessPipe\",k8s_cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "hikaricp_connections_active_percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (application,instance) (hikaricp_connections_active{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"}/hikaricp_connections_max{application=~\"chainAccess.*\"})",
     "legendFormat": "{{application}}-active/max "
    },
    {
     "expr": "sum by (application,instance) (hikaricp_connections_idle{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"}/hikaricp_connections_max{application=~\"chainAccess.*\"})",
     "legendFormat": "{{application}}-idle/max"
    }
   ]
  },
  {
   "title": "tomcat_threads_busy_percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (application,instance) (tomcat_threads_busy{application=~\"chainAccess.*\",name=~\"http-.*\",k8s_cluster=\"$k8s_cluster\"}/tomcat_threads_config_max{application=~\"chainAccess.*\",name=~\"http-.*\",})"
    }
   ]
  },
  {
   "title": "chain_connector_web3jMap_chain_node_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,application,chainId) (chain_connector_web3jMap_chain_node_size{application=\"chainAccessPipe\",k8s_cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "kafka_consumer_transaction_response_time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, topic, application) (delta(kafka_consumer_tx_common_seconds_sum{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"}[2m])/delta(kafka_consumer_tx_common_seconds_count{application=~\"chainAccess.*\"}[2m]) > 0)"
    }
   ]
  },
  {
   "title": "kafka_consumer_transaction_per_minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 33 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, topic, application) (irate(kafka_consumer_tx_common_seconds_count{application=~\"chainAccess.*\",k8s_cluster=\"$k8s_cluster\"}[2m])) * 60"
    }
   ]
  },
  {
   "title": "tx_chain_receive_fail_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,application,chainId,projectId) (tx_chain_receive_fail_time_total{application=\"chainAccessPipe\",k8s_cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "kafka_consumer_tx_common_exception_total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,application,exceptionType) (kafka_consumer_tx_common_exception_time_total{application=\"chainAccessPipe\",k8s_cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "kafka_producer_to_get_txReceipt_total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(kafka_producer_tx_common_time_total{application=\"chainAccessPipe\",type=\"produceToGetTxReceipt\",k8s_cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "kafka_producer_produce_response_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,application,topic,type) (kafka_producer_tx_common_time_total{application=\"chainAccessPipe\",type=\"produceResponse\",k8s_cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "global_exception_total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,application,exceptionType) (global_exception_time_total{application=~\"chainAccess.*\"})"
    }
   ]
  },
  {
   "title": "kafka_producer_produce_error_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,application,topic,type) (kafka_producer_tx_common_time_total{application=\"chainAccessPipe\",type=\"produceError\",k8s_cluster=\"$k8s_cluster\"})"
    }
   ]
  }
 ]
}